[package]
name = "x11rb-async"
version = "0.9.0"
description = "Async Rust bindings to X11"
authors = [
    "Uli Schlachter <psychon@znc.in>",
    "Eduardo Sánchez Muñoz <eduardosm-dev@e64.io>",
    "notgull <jtnunley01@gmail.com>",
]
repository = "https://github.com/psychon/x11rb"
readme = "README.md"
edition = "2018"
license = "MIT OR Apache-2.0"
keywords = ["xcb", "X11"]

[features]
default = ["tokio-support"]
tokio-support = ["tokio", "tokio-util"]

[dependencies]
x11rb-protocol = { version = "0.9.0", path = "../x11rb-protocol" }
async-lock = "2.5"
async-channel = "1.6"
event-listener = "2.5"

[dependencies.futures-util]
version = "0.3"
default-features = false
features = ["io"]

[dependencies.tokio]
version = "1"
features = ["macros", "net", "rt-multi-thread"]
optional = true

[dependencies.tokio-util]
version = "0.7"
features = ["compat"]
optional = true

[dev-dependencies]
smol = "1.2"
